tasks:
  - name: Frontend
    before: npm install -g firebase-tools && npm npm install -g @quasar/cli
    init: cd frontend && npm ci
    command: cd frontend && npm run dev
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
  - port: 8000
    visibility: public