tasks:
  - name: Frontend
    init: cd widget && npm ci
    command: cd widget && npm run dev
# Ports to expose on workspace startup
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8000
    visibility: public